
[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = true 
opacity = 1 

[font]
size = 10.0

[font.bold]
family = "Free Mono"
# family = "Hack Nerd Font"

[font.bold_italic]
# family = "Hack Nerd Font"
family = "Free Mono"

[font.italic]
# family = "Hack Nerd Font"
family = "Free Mono"

[font.normal]
family = "Free Mono"

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]


