
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = true 
opacity = 1 

[font]
size = 8.0

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]


